### ISSUE TITLE
Simulator not loaded for Xcode fresh install 10.2.1

### ISSUE THREAD

**Issue by ganjarpanji** [wswebcreation/start-ios-simulator#2]

**Comment by wswebcreation** [comment]
@ganjarpanji 

Thanks for filing an issue, I've released a new version that should work now. Can you please check it?

https://github.com/wswebcreation/start-ios-simulator/releases/tag/v1.0.0

If it works, can you please close the issue?

Tnx

**Comment by ganjarpanji** [comment]
@wswebcreation 
i run npm install -g start-ios-simulator@1.0.0
then i run start-ios-simulator

got this error :

> (node:27573) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of undefined
    at devices.(anonymous function).map.simulator (/usr/local/lib/node_modules/start-ios-simulator/build/index.js:63:42)
    at Array.map (<anonymous>)
    at Object.keys.filter.forEach.version (/usr/local/lib/node_modules/start-ios-simulator/build/index.js:62:103)
    at Array.forEach (<anonymous>)
    at getAllSimulators (/usr/local/lib/node_modules/start-ios-simulator/build/index.js:62:67)
    at /usr/local/lib/node_modules/start-ios-simulator/build/index.js:22:22
    at Object.<anonymous> (/usr/local/lib/node_modules/start-ios-simulator/build/index.js:41:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
(node:27573) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27573) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by wswebcreation** [comment]
~Hmm, looks like you try to run a simulator that is not installed on your machine, check XCODE and see if the OS version you requested is really installed on your machine~

That's strange, it tells that `availability` is not present anymore in the return list, it is on my machine

```json
"com.apple.CoreSimulator.SimRuntime.iOS-12-2" : [
      {
        "availability" : "(available)",
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 5s",
        "udid" : "4ED0A471-CBC3-487A-A076-A845E55D107A",
        "availabilityError" : ""
      },
      {
        "availability" : "(available)",
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 6",
        "udid" : "F4379FA8-54D6-4B58-93B1-64F3E0B9BB47",
        "availabilityError" : ""
      }
]
```

What do you get back when you run `xcrun simctl list devices --json`?

**Comment by ganjarpanji** [comment]
I get all the simulator list, but when run the program it didnt list all the simulator.

```{
  "devices" : {
    "com.apple.CoreSimulator.SimRuntime.tvOS-13-0" : [
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple TV",
        "udid" : "66C31154-CE95-4085-9B3F-C18A131461E2",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple TV 4K",
        "udid" : "5FC29601-DDB8-4898-9AB6-B9375BC4CBAC",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple TV 4K (at 1080p)",
        "udid" : "A94D703A-C903-4A1B-9FB4-AF7D6EB52511",
        "availabilityError" : "runtime profile not found"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.tvOS-12-2" : [
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "Apple TV",
        "udid" : "96A01000-DF75-4A91-A67E-BE7683FAFA77"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "Apple TV 4K",
        "udid" : "0A570D07-A034-4CAF-B7A8-3ADA1FD0B72C"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "Apple TV 4K (at 1080p)",
        "udid" : "7200EC11-C036-45D2-89E5-1F6C7B573606"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.watchOS-5-2" : [
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "Apple Watch Series 2 - 38mm",
        "udid" : "B34D68B5-B9CC-4705-8669-35362471837F"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "Apple Watch Series 2 - 42mm",
        "udid" : "5FE4CB63-C499-4201-8DE8-2F3778ADF738"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "Apple Watch Series 3 - 38mm",
        "udid" : "26376F56-1F1A-443B-A8A4-D97BBDB5BAF4"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "Apple Watch Series 3 - 42mm",
        "udid" : "4EB3A8D3-A8D9-407D-8A8E-042EDC9640DB"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "Apple Watch Series 4 - 40mm",
        "udid" : "7E54F220-B1EE-4A33-9AC1-343E986D7908"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "Apple Watch Series 4 - 44mm",
        "udid" : "62D1B802-05E2-4FC1-A04A-61E547913D42"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.iOS-13-0" : [
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 8",
        "udid" : "FD9F8685-0BE5-4075-8F43-EDC21AC0F2C1",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 8 Plus",
        "udid" : "2DE298B0-6C41-4079-82EC-99DBDD7A4999",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone Xs",
        "udid" : "C90F1F84-BFB9-4CBA-A4F6-2B5EE5AC316F",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone Xs Max",
        "udid" : "BC3281A9-F595-4A0F-9387-38B4D7C28A1E",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone Xʀ",
        "udid" : "7BA80D1E-9B92-4D7C-8177-48349B51DC34",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Pro (9.7-inch)",
        "udid" : "6FA41A20-3987-4A62-9F95-CE70C9AD1E84",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Pro (11-inch)",
        "udid" : "D3C45A49-7EEC-4924-AF03-2DA23E6B3889",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Pro (12.9-inch) (3rd generation)",
        "udid" : "1F2AB125-26C7-48BE-9A97-F294C668E602",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Air (3rd generation)",
        "udid" : "8098CBBE-CEA1-4006-B6AF-3CDD09B83361",
        "availabilityError" : "runtime profile not found"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.watchOS-6-0" : [
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple Watch Series 2 - 38mm",
        "udid" : "CA2CBD33-C523-42D6-A660-7221B334E0F4",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple Watch Series 2 - 42mm",
        "udid" : "AB8ED5EB-FACF-464E-9C4A-A76ADA7ED7FC",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple Watch Series 3 - 38mm",
        "udid" : "52550CDE-8927-4813-B502-8D39EAD94C77",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple Watch Series 3 - 42mm",
        "udid" : "3EF1E7FE-CFA0-4545-81CC-51364704CFA2",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple Watch Series 4 - 40mm",
        "udid" : "1B6480FF-EC3A-4A28-867E-DB216F641030",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple Watch Series 4 - 44mm",
        "udid" : "B326D619-5773-4E94-B424-C1772A29C640",
        "availabilityError" : "runtime profile not found"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.iOS-12-2" : [
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 5s",
        "udid" : "FA54A371-221E-4320-9726-B99D99514031"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 6",
        "udid" : "B4A2C921-D63E-4D06-9A0E-106A7078DA68"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 6 Plus",
        "udid" : "8FD84B72-2810-41F4-9368-34038F9D9F59"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 6s",
        "udid" : "86709706-9CBC-466A-9CCD-7943F707515B"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 6s Plus",
        "udid" : "D443CF5C-7D5F-451B-ACB6-CD62C583A3D4"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 7",
        "udid" : "5EBF9512-E4D9-4D87-8DD5-025013D896ED"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 7 Plus",
        "udid" : "D79F8192-11ED-48A4-BAF8-A1F97F6A68E4"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 8",
        "udid" : "B152FE23-DB82-46A0-8BC2-134A760B7A2F"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 8 Plus",
        "udid" : "A76FD8AA-DBBC-4FA4-A2EB-9E1264A39B14"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone SE",
        "udid" : "2CF0577E-D58D-4EFF-8991-33A278D0D0A2"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone X",
        "udid" : "0E64CFA0-103B-4F81-B415-19C67DDB4F08"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone Xs",
        "udid" : "2411C391-0A38-42DA-AE3E-B68E32FA364E"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone Xs Max",
        "udid" : "EB72F570-1B69-4BDB-8F5B-65927569BC2F"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone Xʀ",
        "udid" : "28844736-A984-432A-9A37-F0A843AE6E4E"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad Air",
        "udid" : "88445092-55CB-4D94-96FF-0420234AD4DE"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad Air 2",
        "udid" : "323E7D15-3FD8-437F-929E-230D8F8449E2"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad Pro (9.7-inch)",
        "udid" : "99CDD58D-25DC-4BDE-846D-691B21F34AB7"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad Pro (12.9-inch)",
        "udid" : "28F601B1-AF2E-469E-A347-6D672A6697E5"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad (5th generation)",
        "udid" : "33E757A1-A9E3-402D-A1FB-F59A14C0B0C2"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad Pro (12.9-inch) (2nd generation)",
        "udid" : "9B94440E-656D-4F76-A7D5-A5E42CB3DD98"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad Pro (10.5-inch)",
        "udid" : "B652B206-7E49-4721-AC2D-76F04D352470"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad (6th generation)",
        "udid" : "3BC7CD95-E400-4F0C-BE2B-DD1C0E21CC1F"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad Pro (11-inch)",
        "udid" : "53A01AF8-CB6D-45EC-BAA3-0E2B104AC2D6"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad Pro (12.9-inch) (3rd generation)",
        "udid" : "4BFCB619-9728-4FBA-98F5-F69C0CB4F1CA"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad Air (3rd generation)",
        "udid" : "ABF5395C-39F9-4F83-9B36-2F5C3BFB3A1F"
      }
    ]
  }
}

**Comment by ganjarpanji** [comment]
i think u re correct, the field `availability` now is missing somehow in new xcode?
